export const PLAYER_STATUE_IMAGE_SIZE = 256
export const PLAYER_STATUE_NAME_MAX_LENGTH = 30
export const PLAYER_STATUE_MAX_UPLOAD_BYTES = 420 * 1024
export const PLAYER_STATUE_INITIAL_IMAGE_QUALITY = 0.86
export const PLAYER_STATUE_MIN_IMAGE_QUALITY = 0.54
export const PLAYER_STATUE_IMAGE_QUALITY_STEP = 0.08
