export const PLAYER_STATUE_IMAGE_SIZE = 512
export const PLAYER_STATUE_NAME_MAX_LENGTH = 30
export const PLAYER_STATUE_MIN_FOOTPRINT_SIZE = 2
export const PLAYER_STATUE_MAX_UPLOAD_BYTES = 860 * 1024
export const PLAYER_STATUE_INITIAL_IMAGE_QUALITY = 0.86
export const PLAYER_STATUE_MIN_IMAGE_QUALITY = 0.54
export const PLAYER_STATUE_IMAGE_QUALITY_STEP = 0.08
